[package]

name = "bevy_schminput"

version = "0.1.0"
edition = "2021"

[features]
default = []
xr = ["dep:bevy_oxr", "dep:openxr"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["example", "xr_example"]

[dependencies]
bevy = "0.12.1"
bevy-trait-query = "0.4.0"
bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr", optional = true, default-features = false }
openxr = { version = "0.17.1", optional = true }
