[package]
name = "bevy_schminput"
license = "MIT OR BSD-2-Clause-Patent OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = []
xr = ["dep:bevy_oxr", "dep:openxr"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["example", "xr_example"]

[dependencies]
bevy.workspace = true
bevy-trait-query.workspace = true
bevy_oxr = { workspace = true, optional = true }
openxr = { workspace = true, optional = true }

[workspace.dependencies]
bevy = { version = "0.13", default-features = false }
#bevy-trait-query = "0.4.0"
# TODO: wait for update to bevy 0.13 i guess
bevy-trait-query = { git = "https://github.com/RobWalt/bevy-trait-query", rev = "470e123" }
bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr", rev = "8e70df2" }
openxr = "0.18"

[dev-dependencies]

bevy_oxr = { workspace = true,default-features = true }
