[package]
name = "schminput"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Schmarni-Dev/Schminput/"

[features]
default = []
xr = ["dep:bevy_openxr", "dep:bevy_xr", "dep:openxr"]

[workspace]
resolver = "2"
members = ["example", "xr_example"]

[dependencies]
bevy.workspace = true
bevy_openxr = { workspace = true, optional = true }
bevy_xr = { workspace = true, optional = true }
openxr = { workspace = true, optional = true }

[workspace.dependencies]
bevy = { version = "0.13", default-features = false }
bevy_openxr = { git = "https://github.com/Schmarni-Dev/bevy_openxr", branch = "spatial_existence", package = "bevy_openxr" }
bevy_xr = { git = "https://github.com/Schmarni-Dev/bevy_openxr", branch = "spatial_existence", package = "bevy_xr" }
openxr = "0.18"

# bevy_openxr = { path = "../bevy_oxr/crates/bevy_openxr", package = "bevy_openxr" }
# bevy_xr = { path = "../bevy_oxr/crates/bevy_xr", package = "bevy_xr" }

[dev-dependencies]
bevy_openxr = { workspace = true, default-features = true }
