[package]
name = "schminput_schmanager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["example"]

[dependencies]
bevy = "0.12.1"
bevy-trait-query = "0.4.0"
# color-eyre = "0.6.2"
# eyre = "0.6.10"
