[package]
name = "bevy_schminput"
license = "MIT OR BSD-2-Clause-Patent OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = []
xr = ["dep:bevy_oxr", "dep:openxr"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["example", "xr_example"]

[dependencies]
bevy = { version = "0.12.1", default-features = false }
bevy-trait-query = "0.4.0"
bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr", rev = "53af86b", optional = true, default-features = false }
openxr = { git = "https://github.com/Ralith/openxrs", rev = "0177d2d", optional = true }
